"""add created_at fields to core_memory and working_memory

Revision ID: 16c8dbaee964
Revises: 962e790beaf7
Create Date: 2025-12-01 05:43:58.221140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16c8dbaee964'
down_revision: Union[str, Sequence[str], None] = '962e790beaf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from datetime import datetime, timezone
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_index(op.f('ix_tasks_due_dt'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_table('tasks')
    
    # Add columns as nullable first
    op.add_column('core_memory', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('working_memory', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    
    # Set default value for existing rows (use updated_at as fallback, or current time)
    op.execute("UPDATE core_memory SET created_at = COALESCE(updated_at, NOW() AT TIME ZONE 'UTC') WHERE created_at IS NULL")
    op.execute("UPDATE working_memory SET created_at = COALESCE(updated_at, NOW() AT TIME ZONE 'UTC') WHERE created_at IS NULL")
    
    # Alter columns to be NOT NULL
    op.alter_column('core_memory', 'created_at', existing_type=sa.DateTime(timezone=True), nullable=False)
    op.alter_column('working_memory', 'created_at', existing_type=sa.DateTime(timezone=True), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('working_memory', 'created_at')
    op.drop_column('core_memory', 'created_at')
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('due_dt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_from_plan', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('tasks_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_due_dt'), 'tasks', ['due_dt'], unique=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
