"""update DB timestamp columns

Revision ID: 4e25668ea81e
Revises: af97aca27cde
Create Date: 2025-11-02 11:42:25.008536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e25668ea81e'
down_revision: Union[str, Sequence[str], None] = 'af97aca27cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_constraint(op.f('core_memory_embeddings_core_memory_id_key'), 'core_memory_embeddings', type_='unique')
    op.create_index(op.f('ix_core_memory_embeddings_core_memory_id'), 'core_memory_embeddings', ['core_memory_id'], unique=True)
    op.alter_column('episodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_episodes_type'), table_name='episodes')
    op.drop_column('episodes', 'type')
    op.alter_column('oauth_tokens', 'token_expiry',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using='token_expiry AT TIME ZONE \'UTC\'')
    op.alter_column('oauth_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               )
    op.alter_column('oauth_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               )
    op.drop_index(op.f('ix_users_timezone'), table_name='users')
    op.create_index(op.f('ix_users_user_timezone'), 'users', ['user_timezone'], unique=False)
    op.drop_constraint(op.f('working_memory_embeddings_working_memory_id_key'), 'working_memory_embeddings', type_='unique')
    op.create_index(op.f('ix_working_memory_embeddings_working_memory_id'), 'working_memory_embeddings', ['working_memory_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_working_memory_embeddings_working_memory_id'), table_name='working_memory_embeddings')
    op.create_unique_constraint(op.f('working_memory_embeddings_working_memory_id_key'), 'working_memory_embeddings', ['working_memory_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_user_timezone'), table_name='users')
    op.create_index(op.f('ix_users_timezone'), 'users', ['user_timezone'], unique=False)
    op.alter_column('oauth_tokens', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'token_expiry',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('episodes', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_episodes_type'), 'episodes', ['type'], unique=False)
    op.alter_column('episodes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_core_memory_embeddings_core_memory_id'), table_name='core_memory_embeddings')
    op.create_unique_constraint(op.f('core_memory_embeddings_core_memory_id_key'), 'core_memory_embeddings', ['core_memory_id'], postgresql_nulls_not_distinct=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
