"""initial_structure

Revision ID: 803a95fd0d9e
Revises: 
Create Date: 2025-11-22 17:30:30.612611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import sqlmodel
import pgvector.sqlalchemy
import app.security.encrypted_types


# revision identifiers, used by Alembic.
revision: str = '803a95fd0d9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.Integer(), nullable=False),
    sa.Column('tg_chat_id', sa.Integer(), nullable=False),
    sa.Column('name', app.security.encrypted_types.EncryptedTextType(column_label='name'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('user_timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wake_time', sa.Time(), nullable=True),
    sa.Column('bed_time', sa.Time(), nullable=True),
    sa.Column('occupation_json', app.security.encrypted_types.EncryptedJSONType(column_label='occupation_json'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_user_id', name='uq_users_tg_user_id')
    )
    op.create_index(op.f('ix_users_tg_chat_id'), 'users', ['tg_chat_id'], unique=False)
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=False)
    op.create_index(op.f('ix_users_user_timezone'), 'users', ['user_timezone'], unique=False)
    
    op.create_table('core_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('core_text', app.security.encrypted_types.EncryptedTextType(column_label='core_text'), nullable=True),
    sa.Column('sleep_schedule_json', app.security.encrypted_types.EncryptedJSONType(column_label='sleep_schedule_json'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_core_memory_user')
    )
    op.create_index(op.f('ix_core_memory_user_id'), 'core_memory', ['user_id'], unique=False)
    
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', app.security.encrypted_types.EncryptedTextType(column_label='text'), nullable=False),
    sa.Column('metadata_json', app.security.encrypted_types.EncryptedJSONType(column_label='metadata_json'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_created_at'), 'episodes', ['created_at'], unique=False)
    op.create_index(op.f('ix_episodes_user_id'), 'episodes', ['user_id'], unique=False)
    
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', app.security.encrypted_types.EncryptedTextType(column_label='description'), nullable=True),
    sa.Column('cadence', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('reminder_time', sa.Time(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_completed_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_active'), 'habits', ['active'], unique=False)
    op.create_index(op.f('ix_habits_cadence'), 'habits', ['cadence'], unique=False)
    op.create_index(op.f('ix_habits_last_completed_date'), 'habits', ['last_completed_date'], unique=False)
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('encrypted_token_blob', sa.Text(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_oauth_tokens_user_provider')
    )
    op.create_index(op.f('ix_oauth_tokens_provider'), 'oauth_tokens', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_token_expiry'), 'oauth_tokens', ['token_expiry'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_user_id'), 'oauth_tokens', ['user_id'], unique=False)
    
    op.create_table('profile_completeness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('question_frequency', sa.Float(), nullable=False),
    sa.Column('total_questions_asked', sa.Integer(), nullable=False),
    sa.Column('total_interactions', sa.Integer(), nullable=False),
    sa.Column('last_profile_update', sa.DateTime(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_profile_completeness_user')
    )
    op.create_index(op.f('ix_profile_completeness_user_id'), 'profile_completeness', ['user_id'], unique=False)
    
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', app.security.encrypted_types.EncryptedTextType(column_label='description'), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('due_dt', sa.DateTime(), nullable=True),
    sa.Column('created_from_plan', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_due_dt'), 'tasks', ['due_dt'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('morning_window_start', sa.Time(), nullable=True),
    sa.Column('morning_window_end', sa.Time(), nullable=True),
    sa.Column('evening_window_start', sa.Time(), nullable=True),
    sa.Column('evening_window_end', sa.Time(), nullable=True),
    sa.Column('break_mode_active', sa.Boolean(), nullable=False),
    sa.Column('break_mode_until', sa.DateTime(), nullable=True),
    sa.Column('enable_morning_checkin', sa.Boolean(), nullable=False),
    sa.Column('enable_evening_wrapup', sa.Boolean(), nullable=False),
    sa.Column('enable_weekly_plan', sa.Boolean(), nullable=False),
    sa.Column('enable_monthly_plan', sa.Boolean(), nullable=False),
    sa.Column('summary_preferences_json', app.security.encrypted_types.EncryptedJSONType(column_label='summary_preferences_json'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_settings_user')
    )
    op.create_index(op.f('ix_user_settings_break_mode_until'), 'user_settings', ['break_mode_until'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    
    op.create_table('working_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('working_memory_text', app.security.encrypted_types.EncryptedTextType(column_label='working_memory_text'), nullable=True),
    sa.Column('history_order', sa.Integer(), nullable=True),
    sa.Column('decay_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_working_memory_user')
    )
    op.create_index(op.f('ix_working_memory_decay_date'), 'working_memory', ['decay_date'], unique=False)
    op.create_index(op.f('ix_working_memory_history_order'), 'working_memory', ['history_order'], unique=False)
    op.create_index(op.f('ix_working_memory_user_id'), 'working_memory', ['user_id'], unique=False)
    
    op.create_table('working_memory_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('working_memory_text', app.security.encrypted_types.EncryptedTextType(column_label='working_memory_text'), nullable=True),
    sa.Column('history_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_memory_entry_history_order'), 'working_memory_entry', ['history_order'], unique=False)
    op.create_index(op.f('ix_working_memory_entry_user_id'), 'working_memory_entry', ['user_id'], unique=False)
    
    op.create_table('core_memory_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('core_memory_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['core_memory_id'], ['core_memory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_memory_embeddings_core_memory_id'), 'core_memory_embeddings', ['core_memory_id'], unique=True)
    
    op.create_table('episode_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_embeddings_episode_id'), 'episode_embeddings', ['episode_id'], unique=True)
    
    op.create_table('habit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('note', app.security.encrypted_types.EncryptedTextType(column_label='note'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_logs_habit_id'), 'habit_logs', ['habit_id'], unique=False)
    op.create_index(op.f('ix_habit_logs_log_date'), 'habit_logs', ['log_date'], unique=False)
    
    op.create_table('working_memory_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('working_memory_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['working_memory_id'], ['working_memory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_memory_embeddings_working_memory_id'), 'working_memory_embeddings', ['working_memory_id'], unique=True)
    
    op.create_table('working_memory_entry_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('working_entry_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['working_entry_id'], ['working_memory_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_memory_entry_embeddings_working_entry_id'), 'working_memory_entry_embeddings', ['working_entry_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_working_memory_entry_embeddings_working_entry_id'), table_name='working_memory_entry_embeddings')
    op.drop_table('working_memory_entry_embeddings')
    op.drop_index(op.f('ix_working_memory_embeddings_working_memory_id'), table_name='working_memory_embeddings')
    op.drop_table('working_memory_embeddings')
    op.drop_index(op.f('ix_habit_logs_log_date'), table_name='habit_logs')
    op.drop_index(op.f('ix_habit_logs_habit_id'), table_name='habit_logs')
    op.drop_table('habit_logs')
    op.drop_index(op.f('ix_episode_embeddings_episode_id'), table_name='episode_embeddings')
    op.drop_table('episode_embeddings')
    op.drop_index(op.f('ix_core_memory_embeddings_core_memory_id'), table_name='core_memory_embeddings')
    op.drop_table('core_memory_embeddings')
    op.drop_index(op.f('ix_working_memory_entry_user_id'), table_name='working_memory_entry')
    op.drop_index(op.f('ix_working_memory_entry_history_order'), table_name='working_memory_entry')
    op.drop_table('working_memory_entry')
    op.drop_index(op.f('ix_working_memory_user_id'), table_name='working_memory')
    op.drop_index(op.f('ix_working_memory_history_order'), table_name='working_memory')
    op.drop_index(op.f('ix_working_memory_decay_date'), table_name='working_memory')
    op.drop_table('working_memory')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_break_mode_until'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_dt'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_profile_completeness_user_id'), table_name='profile_completeness')
    op.drop_table('profile_completeness')
    op.drop_index(op.f('ix_oauth_tokens_user_id'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_token_expiry'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_provider'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_index(op.f('ix_habits_last_completed_date'), table_name='habits')
    op.drop_index(op.f('ix_habits_cadence'), table_name='habits')
    op.drop_index(op.f('ix_habits_active'), table_name='habits')
    op.drop_table('habits')
    op.drop_index(op.f('ix_episodes_user_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_created_at'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_core_memory_user_id'), table_name='core_memory')
    op.drop_table('core_memory')
    op.drop_index(op.f('ix_users_user_timezone'), table_name='users')
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_tg_chat_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###