"""add_subscription_fields

Revision ID: 962e790beaf7
Revises: 803a95fd0d9e
Create Date: 2025-11-26 12:58:12.169217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '962e790beaf7'
down_revision: Union[str, Sequence[str], None] = '803a95fd0d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_subscription_ends_at'), 'users', ['subscription_ends_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_subscription_ends_at'), table_name='users')
    op.drop_column('users', 'subscription_ends_at')
    # ### end Alembic commands ###
