"""add_scleep_schedule_json_to_core

Revision ID: a69b5321cbcd
Revises: d807fd565f4a
Create Date: 2025-11-03 17:19:22.131833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy
import pgvector
import sqlalchemy
# revision identifiers, used by Alembic.
revision: str = 'a69b5321cbcd'
down_revision: Union[str, Sequence[str], None] = 'd807fd565f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_created_at'), 'episodes', ['created_at'], unique=False)
    op.create_index(op.f('ix_episodes_user_id'), 'episodes', ['user_id'], unique=False)
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('cadence', sa.String(length=20), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('reminder_time', sa.Time(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_completed_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_active'), 'habits', ['active'], unique=False)
    op.create_index(op.f('ix_habits_cadence'), 'habits', ['cadence'], unique=False)
    op.create_index(op.f('ix_habits_last_completed_date'), 'habits', ['last_completed_date'], unique=False)
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('encrypted_token_blob', sa.Text(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_oauth_tokens_user_provider')
    )
    op.create_index(op.f('ix_oauth_tokens_provider'), 'oauth_tokens', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_token_expiry'), 'oauth_tokens', ['token_expiry'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_user_id'), 'oauth_tokens', ['user_id'], unique=False)
    op.create_table('profile_completeness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('question_frequency', sa.Float(), nullable=False),
    sa.Column('total_questions_asked', sa.Integer(), nullable=False),
    sa.Column('total_interactions', sa.Integer(), nullable=False),
    sa.Column('last_profile_update', sa.DateTime(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_profile_completeness_user')
    )
    op.create_index(op.f('ix_profile_completeness_user_id'), 'profile_completeness', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_dt', sa.DateTime(), nullable=True),
    sa.Column('created_from_plan', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_due_dt'), 'tasks', ['due_dt'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('morning_window_start', sa.Time(), nullable=True),
    sa.Column('morning_window_end', sa.Time(), nullable=True),
    sa.Column('evening_window_start', sa.Time(), nullable=True),
    sa.Column('evening_window_end', sa.Time(), nullable=True),
    sa.Column('break_mode_active', sa.Boolean(), nullable=False),
    sa.Column('break_mode_until', sa.DateTime(), nullable=True),
    sa.Column('enable_morning_checkin', sa.Boolean(), nullable=False),
    sa.Column('enable_evening_wrapup', sa.Boolean(), nullable=False),
    sa.Column('enable_weekly_plan', sa.Boolean(), nullable=False),
    sa.Column('enable_monthly_plan', sa.Boolean(), nullable=False),
    sa.Column('summary_preferences_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_settings_user')
    )
    op.create_index(op.f('ix_user_settings_break_mode_until'), 'user_settings', ['break_mode_until'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    op.create_table('episode_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_embeddings_episode_id'), 'episode_embeddings', ['episode_id'], unique=True)
    op.create_table('habit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_logs_habit_id'), 'habit_logs', ['habit_id'], unique=False)
    op.create_index(op.f('ix_habit_logs_log_date'), 'habit_logs', ['log_date'], unique=False)
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('core_memory', sa.Column('sleep_schedule_json', sa.JSON(), nullable=True))
    op.alter_column('core_memory', 'core_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_core_memory_user_id'), 'core_memory', ['user_id'], unique=False)
    op.create_unique_constraint('uq_core_memory_user', 'core_memory', ['user_id'])
    op.drop_column('core_memory', 'created_at')
    op.drop_constraint(op.f('core_memory_embeddings_core_memory_id_key'), 'core_memory_embeddings', type_='unique')
    op.create_index(op.f('ix_core_memory_embeddings_core_memory_id'), 'core_memory_embeddings', ['core_memory_id'], unique=True)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'user_timezone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'occupation_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('users_tg_user_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_tg_chat_id'), 'users', ['tg_chat_id'], unique=False)
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=False)
    op.create_index(op.f('ix_users_user_timezone'), 'users', ['user_timezone'], unique=False)
    op.create_unique_constraint('uq_users_tg_user_id', 'users', ['tg_user_id'])
    op.add_column('working_memory', sa.Column('working_memory_text', sa.String(length=2000), nullable=True))
    op.add_column('working_memory', sa.Column('history_order', sa.Integer(), nullable=True))
    op.add_column('working_memory', sa.Column('decay_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_working_memory_decay_date'), 'working_memory', ['decay_date'], unique=False)
    op.create_index(op.f('ix_working_memory_history_order'), 'working_memory', ['history_order'], unique=False)
    op.create_index(op.f('ix_working_memory_user_id'), 'working_memory', ['user_id'], unique=False)
    op.create_unique_constraint('uq_working_memory_user', 'working_memory', ['user_id'])
    op.drop_column('working_memory', 'content')
    op.drop_column('working_memory', 'created_at')
    op.drop_constraint(op.f('working_memory_embeddings_working_memory_id_key'), 'working_memory_embeddings', type_='unique')
    op.create_index(op.f('ix_working_memory_embeddings_working_memory_id'), 'working_memory_embeddings', ['working_memory_id'], unique=True)
    op.alter_column('working_memory_entry', 'working_memory_text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.drop_index(op.f('ix_working_memory_entry_user_history'), table_name='working_memory_entry')
    op.create_index(op.f('ix_working_memory_entry_history_order'), 'working_memory_entry', ['history_order'], unique=False)
    op.create_index(op.f('ix_working_memory_entry_user_id'), 'working_memory_entry', ['user_id'], unique=False)
    op.create_foreign_key(None, 'working_memory_entry', 'users', ['user_id'], ['id'])
    op.alter_column('working_memory_entry_embeddings', 'embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               nullable=False)
    op.create_index(op.f('ix_working_memory_entry_embeddings_working_entry_id'), 'working_memory_entry_embeddings', ['working_entry_id'], unique=True)
    op.create_foreign_key(None, 'working_memory_entry_embeddings', 'working_memory_entry', ['working_entry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop any foreign key constraints on working_memory_entry_embeddings (unnamed constraints can't be dropped by SQLAlchemy by name None)
    conn = op.get_bind()
    fk_rows = conn.execute(sa.text(
        "SELECT conname FROM pg_constraint WHERE conrelid = 'working_memory_entry_embeddings'::regclass AND contype = 'f';"
    )).all()
    for (conname,) in fk_rows:
        conn.execute(sa.text(f'ALTER TABLE working_memory_entry_embeddings DROP CONSTRAINT "{conname}";'))
    op.drop_index(op.f('ix_working_memory_entry_embeddings_working_entry_id'), table_name='working_memory_entry_embeddings')
    # Converting pgvector to double precision[] can't be done automatically on all setups.
    # To avoid type-cast errors during downgrade we drop and recreate the column as the target type.
    # NOTE: this will remove existing embedding values. Restore from backup if you need them.
    conn.execute(sa.text(
        "ALTER TABLE working_memory_entry_embeddings DROP COLUMN IF EXISTS embedding;"
    ))
    conn.execute(sa.text(
        "ALTER TABLE working_memory_entry_embeddings ADD COLUMN embedding double precision[];"
    ))
    # Drop any foreign key constraints on working_memory_entry
    fk_rows = conn.execute(sa.text(
        "SELECT conname FROM pg_constraint WHERE conrelid = 'working_memory_entry'::regclass AND contype = 'f';"
    )).all()
    for (conname,) in fk_rows:
        conn.execute(sa.text(f'ALTER TABLE working_memory_entry DROP CONSTRAINT "{conname}";'))
    op.drop_index(op.f('ix_working_memory_entry_user_id'), table_name='working_memory_entry')
    op.drop_index(op.f('ix_working_memory_entry_history_order'), table_name='working_memory_entry')
    op.create_index(op.f('ix_working_memory_entry_user_history'), 'working_memory_entry', ['user_id', 'history_order'], unique=False)
    op.alter_column('working_memory_entry', 'working_memory_text',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_working_memory_embeddings_working_memory_id'), table_name='working_memory_embeddings')
    op.create_unique_constraint(op.f('working_memory_embeddings_working_memory_id_key'), 'working_memory_embeddings', ['working_memory_id'], postgresql_nulls_not_distinct=False)
    op.add_column('working_memory', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('working_memory', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_working_memory_user', 'working_memory', type_='unique')
    op.drop_index(op.f('ix_working_memory_user_id'), table_name='working_memory')
    op.drop_index(op.f('ix_working_memory_history_order'), table_name='working_memory')
    op.drop_index(op.f('ix_working_memory_decay_date'), table_name='working_memory')
    op.drop_column('working_memory', 'decay_date')
    op.drop_column('working_memory', 'history_order')
    op.drop_column('working_memory', 'working_memory_text')
    op.drop_constraint('uq_users_tg_user_id', 'users', type_='unique')
    op.drop_index(op.f('ix_users_user_timezone'), table_name='users')
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_tg_chat_id'), table_name='users')
    op.create_unique_constraint(op.f('users_tg_user_id_key'), 'users', ['tg_user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'occupation_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'user_timezone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_core_memory_embeddings_core_memory_id'), table_name='core_memory_embeddings')
    op.create_unique_constraint(op.f('core_memory_embeddings_core_memory_id_key'), 'core_memory_embeddings', ['core_memory_id'], postgresql_nulls_not_distinct=False)
    op.add_column('core_memory', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_core_memory_user', 'core_memory', type_='unique')
    op.drop_index(op.f('ix_core_memory_user_id'), table_name='core_memory')
    op.alter_column('core_memory', 'core_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('core_memory', 'sleep_schedule_json')
    # Recreate apscheduler_jobs if it does not already exist
    conn.execute(sa.text(
        "CREATE TABLE IF NOT EXISTS apscheduler_jobs ("
        "id VARCHAR(191) NOT NULL,"
        "next_run_time DOUBLE PRECISION,"
        "job_state BYTEA NOT NULL,"
        "CONSTRAINT apscheduler_jobs_pkey PRIMARY KEY (id)"
        ");"
    ))
    # Create index if missing
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_apscheduler_jobs_next_run_time ON apscheduler_jobs (next_run_time);"
    ))
    op.drop_index(op.f('ix_habit_logs_log_date'), table_name='habit_logs')
    op.drop_index(op.f('ix_habit_logs_habit_id'), table_name='habit_logs')
    op.drop_table('habit_logs')
    op.drop_index(op.f('ix_episode_embeddings_episode_id'), table_name='episode_embeddings')
    op.drop_table('episode_embeddings')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_break_mode_until'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_dt'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_profile_completeness_user_id'), table_name='profile_completeness')
    op.drop_table('profile_completeness')
    op.drop_index(op.f('ix_oauth_tokens_user_id'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_token_expiry'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_provider'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_index(op.f('ix_habits_last_completed_date'), table_name='habits')
    op.drop_index(op.f('ix_habits_cadence'), table_name='habits')
    op.drop_index(op.f('ix_habits_active'), table_name='habits')
    op.drop_table('habits')
    op.drop_index(op.f('ix_episodes_user_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_created_at'), table_name='episodes')
    op.drop_table('episodes')
    # ### end Alembic commands ###
