"""add_core_fact_and_core_fact_emb

Revision ID: fc08a8eb9107
Revises: 51d1ea426c9b
Create Date: 2025-12-04 16:55:47.732692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'fc08a8eb9107'
down_revision: Union[str, Sequence[str], None] = '51d1ea426c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure the pgvector extension is installed so the `vector` type exists
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # Use an explicit USING clause to cast existing text embeddings to the vector type
    # If embeddings are stored as JSON/text, you may need to convert them to the
    # vector format first or update this SQL to match your storage format.
    op.execute(
        "ALTER TABLE core_fact_embeddings ALTER COLUMN embedding TYPE vector(1536) USING embedding::vector(1536);"
    )
    op.drop_constraint(op.f('core_fact_embeddings_core_fact_id_key'), 'core_fact_embeddings', type_='unique')
    op.create_index(op.f('ix_core_fact_embeddings_core_fact_id'), 'core_fact_embeddings', ['core_fact_id'], unique=True)
    op.create_index(op.f('ix_core_facts_core_memory_id'), 'core_facts', ['core_memory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_facts_core_memory_id'), table_name='core_facts')
    op.drop_index(op.f('ix_core_fact_embeddings_core_fact_id'), table_name='core_fact_embeddings')
    op.create_unique_constraint(op.f('core_fact_embeddings_core_fact_id_key'), 'core_fact_embeddings', ['core_fact_id'], postgresql_nulls_not_distinct=False)
    # Cast vector back to plain text if downgrading; use explicit USING clause
    op.execute(
        "ALTER TABLE core_fact_embeddings ALTER COLUMN embedding TYPE text USING embedding::text;"
    )
    # ### end Alembic commands ###
